# Site settings
title:       Lyle Klyne
email:       lyle.klyne@gmail.com
author:      Lyle Klyne
description: "Design, development, documenting the process."
baseurl:     ""

# Change this to live site URL before posting
url:        "localhost:4000"

# Google analytics
google_analytics: UA-60172340-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: 
twitter_username: lyleklyne
dribbble_username: 
instagram_username: lyleklyne
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    /:title/
paginate:     5
destination: _site/
sass:
  compressed: true


# Gems
gems:
  [jekyll-paginate]